repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: fix-byte-order-marker
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: mixed-line-ending
      - id: check-executables-have-shebangs

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
