#!/usr/bin/env bash

print_info() {
  printf "\033[0;32m==> %s\033[0m\n" "$*"
}

print_error() {
    printf "\033[0;31m%s\033[0m\n" "$*" >&2
    exit 1
}

# -e: exit on error
# -u: exit on undefined variable
set -eu

if ! command -v git >/dev/null; then
    print_info "Installing setup dependency"
    if command -v sudo >/dev/null; then
        sudo apt update && sudo apt install git -y
    else
        apt update && apt install git -y
    fi
fi

if ! chezmoi="$(command -v chezmoi)"; then
    # check current os
    os=$(uname -s)

    case $os in
        "Darwin")
            if command -v brew >/dev/null; then
                bin_dir="$(brew --prefix)/bin"
                chezmoi="${bin_dir}/chezmoi"
                print_info "Installing chezmoi via 🍺 Homebrew to ${chezmoi}"
                sh -c "brew install chezmoi"
            else
                print_error "To install chezmoi, you must have Homebrew installed first."
            fi
            ;;
        "Linux")
            if [ -f "/etc/lsb-release" ] && grep -q "Ubuntu" "/etc/lsb-release"; then
                bin_dir="${HOME}/.local/bin"
                chezmoi="${bin_dir}/chezmoi"
                print_info "Installing chezmoi to ${chezmoi}"
                if command -v curl >/dev/null; then
                    sh -c "$(curl -fsSL get.chezmoi.io)" -- -b "$bin_dir"
                elif command -v wget >/dev/null; then
                    sh -c "$(wget -qO- get.chezmoi.io)" -- -b "$bin_dir"
                else
                    print_error "To install chezmoi, you must have curl or wget installed."
                fi
            else
                print_error "This script only supports Ubuntu for Linux systems."
            fi
            ;;
        *)
            print_error "This script only supports macOS and Ubuntu."
            ;;
    esac
    unset bin_dir
else
    print_info "chezmoi already installed. Continuing to initialization."
fi

# Install 1password before chezmoi
print_info "Installing 1Password-cli before chezmoi configuration..."
exec ".install-1password"

# Current directory where script is running
print_info "Enter your GitHub username to fetch chezmoi setups [default: SwiftyJunnos]: "
read -r username

name=${username:-SwiftyJunnos}

extra_args="--apply"

{
    exec "${chezmoi}" init ${extra_args} ${name}
    print_info "chezmoi initialized at $(${chezmoi} source-path)"
} || {
    print_error "chezmoi initialization failed."
}
