#!/usr/bin/env bash

print_info() {
  printf "\033[0;32m==> %s\033[0m\n" "$*"
}

print_error() {
    printf "\033[0;31m%s\033[0m\n" "$*" >&2
    exit 1
}

# -e: exit on error
# -u: exit on undefined variable
set -eu

if ! chezmoi="$(command -v chezmoi)"; then
    # check current os
    os=$(uname -s)

    case $os in
        "Darwin")
            if command -v brew >/dev/null; then
                print_info "Installing chezmoi via 🍺 Homebrew"
                brew install chezmoi
            else
                print_error "To install chezmoi, you must have Homebrew installed."
            fi
            ;;
        "Linux")
            if [ -f "/etc/lsb-release" ] && grep -q "Ubuntu" "/etc/lsb-release"; then
                bin_dir="${HOME}/.local/bin"
                chezmoi="${bin_dir}/chezmoi"
                print_info "Installing chezmoi to ${chezmoi}"
                if command -v curl >/dev/null; then
                    sh -c "$(curl -fsSL get.chezmoi.io)" -- -b "$bin_dir"
                elif command -v wget >/dev/null; then
                    sh -c "$(wget -qO- get.chezmoi.io)" -- -b "$bin_dir"
                else
                    print_error "To install chezmoi, you must have curl or wget installed."
                fi
            else
                print_error "This script only supports Ubuntu for Linux systems."
            fi

            unset bin_dir
            ;;
        *)
            print_error "This script only supports macOS and Ubuntu"
            ;;
    esac
else
    print_info "chezmoi is already installed"
fi

# Current directory where script is running
print_info "Running chezmoi init"

script_dir="$(dirname -- "$(readlink -f -- "$0")")"
extra_args="--apply --verbose"

max_retries=3
for retry_count in $(seq 0 $max_retries); do
    if "${chezmoi} init --source "${script_dir}" ${extra_args}"; then
        break
    elif [ $retry_count -lt $max_retries ]; then
        print_info "chezmoi init failed... retrying (attempt $((retry_count + 1)) of $max_retries)"
    else
        print_error "chezmoi init failed after $max_retries attempts"
    fi
done
