[".oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
exact = true
refreshPeriod = "72h"

[".oh-my-zsh-custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
exact = true
refreshPeriod = "72h"

[".oh-my-zsh-custom/plugins/zsh-completions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-completions.git"
exact = true
refreshPeriod = "72h"

[".oh-my-zsh-custom/themes/powerlevel10k"]
type = "git-repo"
url = "https://github.com/romkatv/powerlevel10k.git"
exact = true
refreshPeriod = "24h"

[".local/share/fonts"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraMono.tar.xz"
include = ["*.otf", ".ttf"]
exact = true
refreshPeriod = "336h" # 2 weeks
